Disable LDP by default
BadgerTechnologies/ros_astra_camera pull request #16
Opened 2021-12-08 20:51 UTC by coxep

The proximity (LDP) sensor on the stereo S U3 cameras is being triggered by the covers for some robots, effectively disabling the sensor. This commit makes LDP reconfigurable, and disables it by default.

2021-12-08 21:02 UTC, travisariggs requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16)* status: all files reviewed, 2 unresolved discussions (waiting on @coxep)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16#-MqQpVeJ2dT77XTiDPDe):*
Could you add a description about what "LDP" is to the commit message?  You added it in the pull request, but it would be very helpful to have it in the git history.
___
*[cfg/Astra.cfg, line 59 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16#-MqQpjkh1GDTQvM_uD-_:-MqQpjki2DUbfXDdjifR:bjo1bqw) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/85f58024d3248656e1a251c712909e7fe58c7430/cfg/Astra.cfg#L59)):*
> ```INI
> 
> gen.add("disable_emitter", bool_t, 0, "Disable laser emitter", False)
> gen.add("disable_ldp", bool_t, 0, "Disable proximity sensor", True)
> ```

It's generally better to keep the logic positive instead of negative.  Instead of using the term "disable" and setting it "true," setting an "enable" parameter to "false" is preferable.

I see that the parameter immediately above is also done using the inverse.


<!-- Sent from Reviewable.io -->

2021-12-09 14:31 UTC, coxep reviewed
> Dismissed @travisariggs from a discussion.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @travisariggs)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16#-MqQpVeJ2dT77XTiDPDe):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

Could you add a description about what "LDP" is to the commit message?  You added it in the pull request, but it would be very helpful to have it in the git history.
</blockquote></details>

Done
___
*[cfg/Astra.cfg, line 59 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16#-MqQpjkh1GDTQvM_uD-_:-MqUXMhO9bHmz0rzAXUO:bll2jnq) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/85f58024d3248656e1a251c712909e7fe58c7430/cfg/Astra.cfg#L59)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

It's generally better to keep the logic positive instead of negative.  Instead of using the term "disable" and setting it "true," setting an "enable" parameter to "false" is preferable.

I see that the parameter immediately above is also done using the inverse.
</blockquote></details>

I generally agree, but opted to instead go for a more consistent UX by following the style of the prior parameter (which won't be changed; it is being used in multiple places externally, including by level 3 for diagnosing depthcam issues).


<!-- Sent from Reviewable.io -->

2021-12-09 14:40 UTC, travisariggs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16#-:-MqUcp1x7x6PgjT6mijx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @coxep)



<!-- Sent from Reviewable.io -->

2021-12-09 14:40 UTC, travisariggs approved these changes
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @coxep)



<!-- Sent from Reviewable.io -->

2021-12-09 18:59 UTC, merged